# What does physcraper do?

Takes an alignment of any number of taxa.

Finds the mrca from the opentree synthetic tree, so it is not a taxonomic mrca, but a phylogenetic one (whenever there is phylogenetic information).

Blast sequences from the alignment, within the mrca context.

Blast can be done directly on NCBI (very slow, as all blast searches are) or on a copy of the NCBI database installed on a server (way faster).

Blasted sequences come back with NCBI taxonomy ids, so we need to match them to ott ids (using an api call).


Why not use phlawd or supersmart?

They are not integrated to the open tree workflow
physcraper allows tagging




Other type of bootstrap that I think is not yet incorporated into physcraper is the Transfer Bootstrap Expectation (TBE) recently proposed in @lemoine2018renewing.


***- One way to compare two independent phylogenetic trees is to compare them both to
the synthetic OToL and then measure how well they do against each other***

- Currently, the root is determined by finding the parent node of the sequences that do not belong to the ingroup/ search taxon. This ensures a correct rooting of the tree even when the search taxon is more inclusive than the ingroup.
- Conflict information can only be generated in the context of the whole Open Tree of Life. Otherwise, it is not really possible to get conflict data.


figure of unified taxonomy

a table that is a snipet of the csv to show the unified taxonoy for some taxa
also, a screen shoy of the diffeent taxon ides on opentree website works!


**EJM: Currently 2950 studies have treebase data links. It is possible that some/many of these have multiple trees in them, but that is harder to count.**
there are `r tryCatch({rotl::tol_about()$num_source_trees}, error = function(e) {1216})` published trees supporting the resolved nodes of the synthetic tree in the OpenTree website
([See OpenTree's website about](https://tree.opentreeoflife.org/about/synthesis-release/v12.3)).  

Alternative DNA molecular databases could be used for this purpose, either personal or public databases, such as the European Nucleotide Archive or the DNA DataBank of Japan. The code to do this with Physcraper is not yet implemented.
