---
output:
  bookdown::pdf_document2:
    keep_tex: yes
    toc: false
    includes:
      # in_header: preamble.tex
      # after_body: [biorxiv_2019.09.28figcaps.tex]
    # fig_caption: no
geometry: margin = 1in
bibliography: paper.bib
csl: submission-mee/methods-in-ecology-and-evolution.csl
link-citations: yes
# indent: true # this works
# header-includes:
#    - \setlength\parindent{24pt}  # this works too, but I'm gonna indent manually with 4 spaces
# nope, 4 spaces indents are not recognized, they do something else
linestretch: 2
header-includes:
    - \usepackage{caption}
    - \usepackage{blindtext}
    - \usepackage[left]{lineno}
    - \linenumbers
  # - \usepackage{xr}
    # - \usepackage[utf8]{inputenc}
    # - \usepackage[english]{babel}
    # - \usepackage[document]{ragged2e}
# nocite: |
#   @barker2012going, @barker2015new, @burns2014phylogenetics, # @claramunt2015new, @gibb2015new, @Hedges2015, # @hooper2017chromosomal, @Jetz2012, @price2014niche
---

<!-- ``` {r child = '0-header.Rmd'} -->
<!-- ``` -->
\newpage
``` {r child = '1-abstract.Rmd'}
```
\newpage

``` {r child = '2-body.Rmd'}
```
\newpage
\begin{center}
\textsc{References}
\end{center}
